name: Full DevOps Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: chandrulinesmasher/mysampleappv1
  CLUSTER_NAME: chandru-eks
  REGION: ${{ secrets.AWS_REGION }}
  NAMESPACE: myapp

jobs:

# ==========================================
# STAGE 1 – TEST
# ==========================================
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: |
          cd app
          npm install

      - run: echo "No tests configured"


# ==========================================
# STAGE 2 – BUILD & PUSH IMAGE
# ==========================================
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          cd app
          docker build -t $IMAGE_NAME:latest .

      - name: Push
        run: docker push $IMAGE_NAME:latest


# ==========================================
# STAGE 3 – CREATE / UPDATE EKS
# ==========================================
  infra:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd eks-terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd eks-terraform
          terraform apply -auto-approve


# ==========================================
# STAGE 4 – DEPLOY TO EKS
# ==========================================
  deploy:
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - uses: actions/checkout@v4

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect to Cluster
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Restart for new image
        run: |
          kubectl rollout restart deployment myapp -n $NAMESPACE

      - name: Show ingress
        run: |
          kubectl get svc -n ingress-nginx
